# Generated by Django 3.2.4 on 2021-06-18 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='zip_code',
        ),
    ]
