# Generated by Django 3.2.4 on 2021-06-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidApp', '0005_alter_patient_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='reply',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
