# Generated by Django 3.2.4 on 2021-07-18 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidApp', '0009_rename_comments_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
