# Generated by Django 3.2.4 on 2021-07-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidApp', '0011_auto_20210723_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('complaint', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
