# Generated by Django 3.2.4 on 2021-07-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidApp', '0012_support'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='city',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='days_open',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='open_time',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='state',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='address',
            field=models.TextField(default='1234 Street Name, City, State 01234', max_length=100),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='hours',
            field=models.TextField(default='24 hours', max_length=100),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='website',
            field=models.URLField(max_length=100),
        ),
    ]
