# Generated by Django 3.2.4 on 2021-07-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidApp', '0013_auto_20210727_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='city',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='days_open',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='open_time',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='state',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='clinic',
            name='address',
            field=models.TextField(default='1234 Street Name, City, State, 01234', max_length=250),
        ),
        migrations.AddField(
            model_name='clinic',
            name='hours',
            field=models.TextField(default='24 hours', max_length=100),
        ),
        migrations.AddField(
            model_name='clinic',
            name='website',
            field=models.URLField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='zip_code',
            field=models.CharField(default='01234', max_length=20),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='zip_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='address',
            field=models.TextField(default='1234 Street Name, City, State 01234', max_length=250),
        ),
    ]
